Minor: Consistently use printUsage(), add newline before bottom hint, do block-wide redirection

diff --git a/bin/collapseDuplicates b/bin/collapseDuplicates
--- a/bin/collapseDuplicates
+++ b/bin/collapseDuplicates
@@ -12,7 +12,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -83,17 +83,17 @@ do
 	--match-accumulated|-M)	shift; types+=(match-accumulate); patterns+=("${1:?}"); replacements+=('&'); shift;;
 	--replacement|-r)	shift
 				if [ ${#types[@]} -eq 0 ]; then
-				    echo >&2 "Need -e|--regexp|-a|--accumulate|-m|--match|-M|--match-accumulated PATTERN before passing REPLACEMENT."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-a|--accumulate|-m|--match|-M|--match-accumulated PATTERN before passing REPLACEMENT."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				replacements[-1]="$1"
 				shift
 				;;
 	--unbuffered|-u)	shift; isBuffered=;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/extractMatches b/bin/extractMatches
--- a/bin/extractMatches
+++ b/bin/extractMatches
@@ -19,7 +19,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -151,11 +151,11 @@ HELPTEXT
 singleRenderCheck()
 {
     if [ "$render" ]; then
-	echo >&2 "ERROR: There can be only one --to / --grep-..."
-	echo >&2
-	printShortUsage "$1" >&2
+	echo "ERROR: There can be only one --to / --grep-..."
+	echo
+	printUsage "$1"
 	exit 2
-    fi
+    fi >&2
 }
 
 getCountPrefix()
@@ -272,11 +272,11 @@ do
 	--reset-name)		shift; types+=(reset-name); patterns+=("${1:?}"); replacements+=('&'); globals+=(0); others+=(''); names+=('') priorities+=(0); shift;;
 	--reset|-x)		shift
 				if [ ${#types[@]} -eq 0 ] || [ "${types[-1]}" = reset-name ]; then
-				    echo >&2 "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing RESET-PATTERN."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing RESET-PATTERN."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				types+=(reset); patterns+=("${1:?}"); replacements+=('&'); globals+=("${globals[-1]}"); others+=(''); priorities+=("${priorities[-1]}")	# Don't copy reset-other; as a following --reset-other can independently add a trigger for RESET-PATTERN.
 				countPatternAppendix=; [ "${types[-2]}" = count ] && countPatternAppendix="-${patterns[-2]}"
 				if [ "${names[-1]}" ]; then
@@ -289,55 +289,55 @@ do
 				;;
 	--reset-other|-k)	shift
 				if [ ${#types[@]} -eq 0 ] || [ "${types[-1]}" = reset-name ]; then
-				    echo >&2 "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing --reset-other NAME."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing --reset-other NAME."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				others[-1]="$1"
 				shift
 				;;
 	--replacement|-r)	shift
 				if [ ${#types[@]} -eq 0 ] || [[ "${types[-1]}" = reset?(-name) ]]; then
-				    echo >&2 "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing REPLACEMENT."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing REPLACEMENT."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				replacements[-1]="$1"
 				shift
 				;;
 	--global|-g)		shift
 				if [ ${#types[@]} -eq 0 ] || [ "${types[-1]}" = reset ]; then
-				    echo >&2 "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing -g|--global."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-c|--count|-M|--match-count PATTERN before passing -g|--global."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				globals[-1]=1
 				;;
 	--name|-n)		shift
 				if [ ${#types[@]} -eq 0 ]; then
-				    echo >&2 "Need -e|--regexp|-c|--count|-M|--match-count|--reset-name PATTERN before passing NAME."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-c|--count|-M|--match-count|--reset-name PATTERN before passing NAME."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				names[-1]="$1"
 				shift
 				;;
 	--priority|-p)		shift
 				if [ ${#types[@]} -eq 0 ]; then
-				    echo >&2 "Need -e|--regexp|-c|-count|-M|--match-count|--reset-name PATTERN before passing PRIORITY."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "Need -e|--regexp|-c|-count|-M|--match-count|--reset-name PATTERN before passing PRIORITY."
+				    echo
+				    printUsage "$0"
 				    exit 2
 				elif [[ "$1" != ?(-)+([0-9]) ]]; then
-				    echo >&2 "PRIORITY must be a number."
-				    echo >&2
-				    printShortUsage "$0" >&2
+				    echo "PRIORITY must be a number."
+				    echo
+				    printUsage "$0"
 				    exit 2
-				fi
+				fi >&2
 				priorities[-1]="$1"
 				shift
 				;;
@@ -352,7 +352,7 @@ do
 				    count-desc)	reportOrder='compareByCount';;
 				    *)		echo >&2 "ERROR: Invalid report order."
 						echo >&2
-						printShortUsage "$0" >&2
+						printUsage "$0" >&2
 						exit 2
 						;;
 				esac
@@ -360,16 +360,16 @@ do
 				;;
 	--name-percentages|-%)	shift; namePercentages+=("$1"); shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
 if [ ${#types[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No -e|--regexp|-c|--count|-M|--match-count|-x|--reset passed.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: No -e|--regexp|-c|--count|-M|--match-count|-x|--reset passed.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 originalRender="${render:=highlight}"
 if [ "$render" = 'notify' ]; then
     if [ -z "$EXTRACTMATCHES_NOTIFY_COMMANDLINE" ] && ! which "$EXTRACTMATCHES_NOTIFY_SEND" >/dev/null 2>&1; then
@@ -400,7 +400,7 @@ fi
 if [ "$render" = 'flash' ] && [ "$isBuffered" ]; then
     echo >&2 'ERROR: Flash reporting must be combined with --unbuffered.'
     echo >&2
-    printShortUsage "$0" >&2
+    printUsage "$0" >&2
     exit 2
 elif [ "$render" = 'command' ]; then
     if [ -z "$EXTRACTMATCHES_COMMANDLINE" ]; then
diff --git a/bin/sampleLines b/bin/sampleLines
--- a/bin/sampleLines
+++ b/bin/sampleLines
@@ -29,7 +29,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -219,11 +219,11 @@ do
     esac
 done
 if [ ! "$isInline" -a -n "$inlinePrefix" ]; then
-    echo >&2 'ERROR: --inline-prefix only works in conjunction with an --inline-... option.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: --inline-prefix only works in conjunction with an --inline-... option.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 if [ "$isInline" ]; then prefix="[1G[2K$inlinePrefix"; suffix=; finalizer='\n'; fi
 [ "$isClear" ] && finalizer='[1G[2K'
 
diff --git a/bin/secondsToDuration b/bin/secondsToDuration
--- a/bin/secondsToDuration
+++ b/bin/secondsToDuration
@@ -5,6 +5,7 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[--] SECONDS [...] [-?|-h|--help]'
+    echo
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-s|--skip SKIP&PATTERN [...]] [-m|--match MATCH&PATTERN [...]] [-w|--width WIDTH]'
 }
 printUsage()
@@ -12,7 +13,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -52,7 +53,7 @@ do
 	--match|-m)	shift; matchPattern="${matchPattern}${matchPattern:+|}${1:?}"; shift;;
 	--width|-w)	shift; width="$1"; shift;;
 	--)		break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
diff --git a/bin/timestampTally b/bin/timestampTally
--- a/bin/timestampTally
+++ b/bin/timestampTally
@@ -13,7 +13,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -151,7 +151,7 @@ do
 			    shift; singleEntryDuration="$(timeToSeconds "$1")" || exit $?; shift;;
 	--tally)	    shift
 			    if [ "$isSummarize" ]; then
-				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printShortUsage "$0"; } >&2
+				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printUsage "$0"; } >&2
 				exit 2
 			    fi
 			    tally="$1"
@@ -159,7 +159,7 @@ do
 			    ;;
 	--summarize)	    shift
 			    if [ ! "$isSummarize" ] && [ -n "$tally" ]; then
-				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printShortUsage "$0"; } >&2
+				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printUsage "$0"; } >&2
 				exit 2
 			    fi
 			    tally="$1"
@@ -170,31 +170,31 @@ do
 			    keepTimestamp="$1"
 			    case "$keepTimestamp" in
 				start|end|both-concatenated|both-separate)  ;;
-				*)  { printf 'ERROR: Invalid value for --keep-timestamp: %s\n' "$keepTimestamp"; echo; printShortUsage "$0"; } >&2; exit 2;;
+				*)  { printf 'ERROR: Invalid value for --keep-timestamp: %s\n' "$keepTimestamp"; echo; printUsage "$0"; } >&2; exit 2;;
 			    esac
 			    shift
 			    ;;
 	--)		    shift; break;;
-	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		    break;;
     esac
 done
 if [ -n "$maxRecordDuration" -a "$maxDifference" = 0 ]; then
-    echo >&2 'ERROR: --max-record-duration can only be used together with --max-difference.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: --max-record-duration can only be used together with --max-difference.'
+    echo
+    printUsage "$0"
     exit 2
 elif [ -n "$maxRecordLength" -a "$maxDifference" = 0 ]; then
-    echo >&2 'ERROR: --max-record-length can only be used together with --max-difference.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: --max-record-length can only be used together with --max-difference.'
+    echo
+    printUsage "$0"
     exit 2
 elif [ "$isSummarize" ] && [ "$keepTimestamp" = 'both-separate' ]; then
-    echo >&2 'ERROR: Cannot combine --keep-timestamp both-separate with --summarize.'
-    echo >&2
-    printShortUsage "$0" >&2
+    echo 'ERROR: Cannot combine --keep-timestamp both-separate with --summarize.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 [ -z "$singleEntryDuration" ] && singleEntryDuration=$entryDuration
 
 awk \
diff --git a/bin/truncate-lines b/bin/truncate-lines
--- a/bin/truncate-lines
+++ b/bin/truncate-lines
@@ -9,7 +9,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -23,7 +23,8 @@ check per expression. There can be a fallback expression with --else, and the
 file can even be removed if nothing changed its contents.
 HELPDESCRIPTION
     echo
-    printShortUsage "$1" cat <<HELPTEXT
+    printShortUsage "$1"
+    cat <<HELPTEXT
 --verbose|-v		Show detailed results for each file.
 --verbose-color		Same, but with different colors depending on action taken.
 --consider ADDRESS	If the FILE does not match ADDRESS (which often is a sed
@@ -75,7 +76,7 @@ do
 	-n|--regexp-extended|-r|--null-data|-z)	allSedArguments+=("$1");      let matchSedArgumentNum["$currentMatch"]+=1; shift;;
 	-e|-f)					allSedArguments+=("$1" "$2"); let matchSedArgumentNum["$currentMatch"]+=2; matchSedHasExpression["$currentMatch"]=t; shift; shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		if [ "$currentMatch" ] && [ ! "${matchSedHasExpression["$currentMatch"]}" ]; then
 			    allSedArguments+=("$1")
 			    let matchSedArgumentNum["$currentMatch"]+=1
diff --git a/bin/updateTextBlock b/bin/updateTextBlock
--- a/bin/updateTextBlock
+++ b/bin/updateTextBlock
@@ -40,7 +40,7 @@ printUsage()
     # This is the short help when launched with no or incorrect arguments.
     # It is printed to stderr to avoid accidental processing.
     printShortUsage "$1" >&2
-    printf >&2 'Try %q --help for more information.\n' "$(basename "$1")"
+    printf >&2 '\nTry %q --help for more information.\n' "$(basename "$1")"
 }
 printLongUsage()
 {
@@ -80,7 +80,7 @@ do
 	--marker|-m)		shift; beginMarker="$1"; endMarker="$1"; shift;;
 	--begin-marker|-b)	shift; beginMarker="$1"; isCustomBeginMarker='true'; shift;;
 	--end-marker|-e)	shift; endMarker="$1"; isCustomEndMarker='true'; shift;;
-	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printShortUsage "$0"; } >&2; exit 2;;
+	-*)			{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)			break;;
     esac
 done
