Generalization: Refactoring: Major: Move expiration logic to durationWithAdjustmentToSeconds
Though it's just somewhat related to the timespan adaptation itself, durationWithAdjustmentToSeconds was created to reduce the boilerplate code that the various clients have to implement, and this move resonates perfectly with that.
One driving factor was that durationWithAdjustmentToSeconds already uses bc for the adaptation, so it could (in the future) reuse a coproc for the expiration comparison, whereas sampleLines already has a coproc for durationWithAdjustmentToSeconds, and would need a second one (which Bash officially doesn't support and prints a "warning: execute_coproc: coproc [2463275:BC] still exists") for bc.
Clients now just need to communicate with a single adjuster, both for the adjusting of the configured timespan, and now also speaking a small protocol with these actions:
- set EXPIRY-TIMESPAN [INITIAL-DELAY] for priming the expiry machine, returning the start time / seconds (for debugging purposes in the client, and as a coproc has to return something).
- reset EXPIRY-TIMESPAN for restarting the expiry machine, returning the same as the set action
- check for a stateful check again the EXPIRY-TIMESPAN previously set by [re]set
All timestamping is now encapsulated by durationWithAdjustmentToSeconds.

An adjustment could automatically update the expiryTimespan, but I didn't implement that because
1. adjustments could also happen for other purposes
2. it's cleaner for the client to keep control of the timespan, as functionality like sampleLines's --reset-on might affect the timespan, too, and there's a risk that the sending of that update to durationWithAdjustmentToSeconds might be forgotten

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/durationWithAdjustmentToSeconds b/bin/durationWithAdjustmentToSeconds
--- a/bin/durationWithAdjustmentToSeconds
+++ b/bin/durationWithAdjustmentToSeconds
@@ -35,6 +35,10 @@ printShortUsage()
     # skim the long one.
     printf 'Usage: [DURATIONWITHADJUSTMENTTOSECONDS_ACCEPT_FRACTIONAL=1|t|true] %q %s\n' "$(basename "$1")" "[-N|--no-adjustment] $formatParameter [...] [-?|-h|--help]"
     printf "Usage: printf '%%s\\\\t%%s\\\\n' %s | %q %s\\n" "$formatParameter [...]" "$(basename "$1")" '[-u|--unbuffered] [-N|--no-adjustment]'
+    echo
+    printf "Usage: printf 'set\\\\tEXPIRY-TIMESPAN[\\\\tINITIAL-DELAY]\\\\n' | %q ...\\n" "$(basename "$1")"
+    printf "Usage: printf 'reset\\\\tEXPIRY-TIMESPAN\\\\n' | %q ...\\n" "$(basename "$1")"
+    printf "Usage: printf 'check\\\\n' | %q ...\\n" "$(basename "$1")"
 }
 printUsage()
 {
@@ -91,16 +95,20 @@ printfWithSeparator()
 
 calculate()
 {
-    local calculation; printf -v calculation '%.10f %s' "$timespan" "${1:?}"
+    local originalTimespan="${1:?}"; shift
+    local calculation; printf -v calculation '%.10f %s' "$originalTimespan" "${1:?}"
+
     [ "$DURATIONWITHADJUSTMENTTOSECONDS_ACCEPT_FRACTIONAL" ] \
 	&& calculation="scale=10; $calculation" \
 	|| calculation="scale=10; result = ${calculation}; scale = 0; (result + 0.5) / 1"
 
-    local result; result=$(printf '%s\n' "$calculation" | bc) || { printf >&2 'ASSERT: Calculation failed: %s\n' "$calculation"; exit 3; }
-    [[ "$result" = -* ]] && result=0	# Don't allow negative results.
-    [[ "$result" = .* ]] && result="0$result"	# bc omits a leading zero for fractional numbers smaller than one.
-    [[ "$result" = *.* ]] && result=${result%%?(.)+(0)}	# Remove trailing zeros and the decimal point if there are no more digits after it.
-    printfWithSeparator '%s' "$result"
+    local updatedTimespan; updatedTimespan=$(printf '%s\n' "$calculation" | bc) || { printf >&2 'ASSERT: Calculation failed: %s\n' "$calculation"; exit 3; }
+    [[ "$updatedTimespan" = -* ]] && updatedTimespan=0	# Don't allow negative results.
+    [[ "$updatedTimespan" = .* ]] && updatedTimespan="0$updatedTimespan"	# bc omits a leading zero for fractional numbers smaller than one.
+    [[ "$updatedTimespan" = *.* ]] && updatedTimespan=${updatedTimespan%%?(.)+(0)}	# Remove trailing zeros and the decimal point if there are no more digits after it.
+
+    printfWithSeparator '%s' "$updatedTimespan"
+    case ",${DEBUG:-}," in *,durationWithAdjustmentToSeconds:adjust,*) printf >&2 '%sdurationWithAdjustmentToSeconds (adjust): %s -> %s\n' "$PS5" "$originalTimespan" "$updatedTimespan";; esac
 }
 
 export DURATIONTOSECONDS_ACCEPT_FRACTIONAL="$DURATIONWITHADJUSTMENTTOSECONDS_ACCEPT_FRACTIONAL"
@@ -134,7 +142,7 @@ convert()
 
     if [ -n "$adjustment" ]; then
 	if [ "$isAdjust" ]; then
-	    calculate "${adjustmentCalculation:-$adjustment}"
+	    calculate "$timespan" "${adjustmentCalculation:-$adjustment}"
 	else
 	    printfWithSeparator '%s\t%s' "$timespan" "$adjustment"
 	fi
@@ -143,11 +151,57 @@ convert()
     fi
 }
 
+expiryTimespan=
 process()
 {
     local status=0
     [ $# -gt 0 ] || return 0
     case "$1" in
+	set)
+	    shift
+	    expiryTimespan="${1:?}"; shift
+	    local initialDelay="${1:-0}"; shift
+	    if [[ "${expiryTimespan}${initialDelay}" = *.* ]]; then
+		# First expiry should happen immediately / after initial delay, so subtract the
+		# expiry timespan from the current time and add the initial delay.
+		startTime=$(awk 'BEGIN{ printf "%f\n", ARGV[1] - ARGV[2] + ARGV[3]; }' "$(date +%s.%N)" "$expiryTimespan" "$initialDelay")
+		printf '🕔 %s\n' "$startTime"
+	    else
+		# First expiry should happen immediately / after initial delay, so prime the
+		# counter with the expiry timespan minus the initial delay.
+		local startSeconds=$((expiryTimespan - initialDelay))
+		SECONDS=$startSeconds
+		unset startTime
+		printf '⏱️ %d\n' "$startSeconds"
+	    fi
+	    ;;
+	reset)
+	    shift
+	    expiryTimespan="${1:?}"; shift
+	    if [[ "$expiryTimespan" = *.* ]]; then
+		: ${startTime:=$(date +%s.%N)}
+		printf '🕔 %s\n' "$startTime"
+	    else
+		SECONDS=0
+		unset startTime
+		printf '⏱️ 0\n'
+	    fi
+	    ;;
+	check)
+	    shift
+	    if [ -n "$startTime" ]; then
+		endTime=$(date +%s.%N)
+		local timeComparison; printf -v timeComparison '%.10f - %.10f >= %.10f' "$endTime" "$startTime" "${expiryTimespan:?}"
+		local result; result=$(printf '%s\n' "$timeComparison" | bc) || { echo >&2 "ASSERT: Time difference comparison should succeed: $timeComparison"; exit 3; }
+		case ",${DEBUG:-}," in *,durationWithAdjustmentToSeconds:expiry,*) printf >&2 '%sdurationWithAdjustmentToSeconds (expiry): %s = %d\n' "$PS5" "$timeComparison" "$result";; esac
+		[ $result -ne 0 ] && startTime=$endTime	# Optimization: Set new start time on expiry, so "expiry reset" doesn't have to obtain the time again.
+	    else
+		[ $SECONDS -ge ${expiryTimespan:?} ]
+	    fi \
+		&& echo 'expired' \
+		|| echo 'remaining'
+	    ;;
+
 	*)  while [ $# -gt 0 ]
 	    do
 		[ $# -eq 1 ] && SEPARATOR=$'\n'
