extractMatchesToPanel: Robustness: Also check for $TERMID before proceeding
When running without a terminal (cron job, Conky), no notification is possible. Let's detect that early and avoid the invocation chain completely.

diff --git a/bin/extractMatchesToPanel b/bin/extractMatchesToPanel
--- a/bin/extractMatchesToPanel
+++ b/bin/extractMatchesToPanel
@@ -17,6 +17,9 @@ esac
 if ! type -t titleupdate >/dev/null; then
     echo >&2 'ERROR: titleupdate is not available.'
     exit 3
+elif [ -z "$TERMID" ]; then
+    echo >&2 'ERROR: Cannot notify via titleupdate; TERMID not defined.'
+    exit 3
 fi
 
 EXTRACTMATCHES_COMMAND_UPDATE_DELAY=${EXTRACTMATCHES_PANEL_UPDATE_DELAY:-0} \
