Check that only one renderer is passed (via --to / --grep-only-matching)

diff --git a/bin/extractMatches b/bin/extractMatches
--- a/bin/extractMatches
+++ b/bin/extractMatches
@@ -129,6 +129,15 @@ Example:
 HELPTEXT
     printf '%q %s\n' "$(basename "$1")" '--regexp "FATAL:.*" --name err --regexp "ERROR:.*" --name err --count Restarted --reset Restarted --name err'
 }
+singleRenderCheck()
+{
+    if [ "$render" ]; then
+	echo >&2 "ERROR: There can be only one --to / --grep-..."
+	echo >&2
+	printShortUsage "$1" >&2
+	exit 2
+    fi
+}
 
 getCountPrefix()
 {
@@ -200,7 +209,7 @@ EXEC=exec
 : ${EXTRACTMATCHES_FLASH_REPEATS:=3}
 : ${EXTRACTMATCHES_HIGHLIGHT_PREFIX=[07m}
 : ${EXTRACTMATCHES_HIGHLIGHT_SUFFIX=[0m}
-render='highlight'
+render=
 skipPattern=
 typeset -a types=()
 typeset -a patterns=()
@@ -216,8 +225,8 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
-	--to|-t)	shift; render="$1"; shift;;
-	--grep-only-matching)	shift; render='/dev/stdout'; isQuiet=t; EXTRACTMATCHES_FILE_UPDATE_DELAY=0;;
+	--to|-t)	shift; singleRenderCheck "$0"; render="$1"; shift;;
+	--grep-only-matching)	shift; singleRenderCheck "$0"; render='/dev/stdout'; isQuiet=t; EXTRACTMATCHES_FILE_UPDATE_DELAY=0;;
 	--skip|-s)	shift; skipPattern="${skipPattern}${skipPattern:+|}${1:?}"; shift;;
 	--regexp|-e)		shift; types+=(regexp); patterns+=("${1:?}"); replacements+=('&'); globals+=(0); others+=(''); names+=('') priorities+=(0); shift;;
 	--count|-c)		shift; types+=(count); patterns+=("${1:?}"); replacements+=('&'); globals+=(0); others+=(''); names+=('') priorities+=(0); shift;;
@@ -328,7 +337,7 @@ if [ ${#types[@]} -eq 0 ]; then
     printShortUsage "$0" >&2
     exit 2
 fi
-originalRender="$render"
+originalRender="${render:=highlight}"
 if [ "$render" = 'notify' ]; then
     if [ -z "$EXTRACTMATCHES_NOTIFY_COMMANDLINE" ] && ! which "$EXTRACTMATCHES_NOTIFY_SEND" > /dev/null 2>&1; then
 	printf >&2 'ERROR: notify-send command (%s) not found.\n' "$EXTRACTMATCHES_NOTIFY_SEND"
