ENH: Allow clearing the overlay at the end with --clear

diff --git a/bin/extractMatches b/bin/extractMatches
--- a/bin/extractMatches
+++ b/bin/extractMatches
@@ -12,7 +12,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-u|--unbuffered] [-q|--quiet] [-y|--summary|-Y|--summary-only] [[--name-percentage-threshold N] -%|--name-percentages NAME|/NAME-PATTERN/ [...]] [-t|--to overlay|title|stderr|concatenated|command|notify|highlight|flash|FILE|--grep-only-matching|--grep-count] [-s|--skip PATTERN [...]] [-o|--report-order by-arg|count-desc] (-e|--regexp [-r|--replacement REPLACEMENT] [-g|--global] [-p|--priority N] [-n|--name NAME] [-k|--reset-other NAME|/NAME-PATTERN/] [-x|--reset RESET-PATTERN [-k|--reset-other NAME|/NAME-PATTERN/]])(-c|--count|-M|--match-count [-r|--replacement REPLACEMENT] [-g|--global] [-p|--priority N] [-n|--name NAME] [-k|--reset-other NAME|/NAME-PATTERN/] [-x|--reset RESET-PATTERN [-k|--reset-other NAME|/NAME-PATTERN/]])(--reset-name PATTERN [-g|--global] -n|--name NAME|/NAME-PATTERN/) [...] [--] FILE [...][-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-u|--unbuffered] [-q|--quiet] [-y|--summary|-Y|--summary-only] [[--name-percentage-threshold N] -%|--name-percentages NAME|/NAME-PATTERN/ [...]] [-t|--to overlay [--clear]|title|stderr|concatenated|command|notify|highlight|flash|FILE|--grep-only-matching|--grep-count] [-s|--skip PATTERN [...]] [-o|--report-order by-arg|count-desc] (-e|--regexp [-r|--replacement REPLACEMENT] [-g|--global] [-p|--priority N] [-n|--name NAME] [-k|--reset-other NAME|/NAME-PATTERN/] [-x|--reset RESET-PATTERN [-k|--reset-other NAME|/NAME-PATTERN/]])(-c|--count|-M|--match-count [-r|--replacement REPLACEMENT] [-g|--global] [-p|--priority N] [-n|--name NAME] [-k|--reset-other NAME|/NAME-PATTERN/] [-x|--reset RESET-PATTERN [-k|--reset-other NAME|/NAME-PATTERN/]])(--reset-name PATTERN [-g|--global] -n|--name NAME|/NAME-PATTERN/) [...] [--] FILE [...][-?|-h|--help]'
 }
 printUsage()
 {
@@ -40,6 +40,7 @@ HELPDESCRIPTION
 			    terminal (current line with --quiet, and also no
 			    default highlighting then, so that combination looks
 			    more like live reporting than an actual overlay).
+    --clear		    Clear the overlay at the end.
     --to|-t title	    Report in the terminal's window title via ANSI
 			    escape sequences.
     --to|-t stderr	    Report as a single concatenated line (like with
@@ -208,12 +209,14 @@ literalAwkExtendedPattern()
 : ${EXTRACTMATCHES_OVERLAY_SUFFIX=][0m}
 : ${EXTRACTMATCHES_OVERLAY_ERASE=}
 : ${EXTRACTMATCHES_OVERLAY_RETURN=[u}
+: ${EXTRACTMATCHES_OVERLAY_CLEAR=[s[1;1H[0K[u}
 : ${EXTRACTMATCHES_OVERLAY_QUIET_JUMP=[1G}
 : ${EXTRACTMATCHES_OVERLAY_QUIET_PREFIX=[}
 : ${EXTRACTMATCHES_OVERLAY_QUIET_SEPARATOR=|}
 : ${EXTRACTMATCHES_OVERLAY_QUIET_SUFFIX=]}
 : ${EXTRACTMATCHES_OVERLAY_QUIET_ERASE=[0K}
 : ${EXTRACTMATCHES_OVERLAY_QUIET_RETURN=}
+: ${EXTRACTMATCHES_OVERLAY_QUIET_CLEAR=[1G[0K}
 case "$TERM" in
     screen*)
 	: ${EXTRACTMATCHES_TITLE_SET=']2;'}
@@ -273,6 +276,7 @@ currentNamePercentageThreshold=0
 typeset -a namePercentages=()
 typeset -a namePercentageThresholds=()
 isBuffered=t; [ -t 1 ] && isBuffered=
+isClear=
 isQuiet=
 reportOrder='compareByKeyArgumentOrder'
 while [ $# -ne 0 ]
@@ -359,6 +363,7 @@ do
 				shift
 				;;
 	--unbuffered|-u)	shift; isBuffered=;;
+	--clear)		shift; isClear=t;;
 	--quiet|-q)		shift; isQuiet=t;;
 	--summary-only|-Y)	isQuiet=t
 				;&
@@ -423,6 +428,7 @@ if [ "$isQuiet" ]; then
     extractmatchesOverlaySuffix="$EXTRACTMATCHES_OVERLAY_QUIET_SUFFIX"
     extractmatchesOverlayErase="$EXTRACTMATCHES_OVERLAY_QUIET_ERASE"
     extractmatchesOverlayReturn="$EXTRACTMATCHES_OVERLAY_QUIET_RETURN"
+    extractmatchesOverlayClear="$EXTRACTMATCHES_OVERLAY_QUIET_CLEAR"
 else
     extractmatchesOverlayJump="$EXTRACTMATCHES_OVERLAY_JUMP"
     extractmatchesOverlayPrefix="$EXTRACTMATCHES_OVERLAY_PREFIX"
@@ -430,15 +436,21 @@ else
     extractmatchesOverlaySuffix="$EXTRACTMATCHES_OVERLAY_SUFFIX"
     extractmatchesOverlayErase="$EXTRACTMATCHES_OVERLAY_ERASE"
     extractmatchesOverlayReturn="$EXTRACTMATCHES_OVERLAY_RETURN"
+    extractmatchesOverlayClear="$EXTRACTMATCHES_OVERLAY_CLEAR"
 fi
 if [ "$render" = 'flash' ] && [ "$isBuffered" ]; then
-    echo >&2 'ERROR: Flash reporting must be combined with --unbuffered.'
-    echo >&2
-    printUsage "$0" >&2
+    echo 'ERROR: Flash reporting must be combined with --unbuffered.'
+    echo
+    printUsage "$0"
+    exit 2
+elif [ "$render" != 'overlay' ] && [ "$isClear" ]; then
+    echo 'ERROR: --clear must be combined with --to overlay.'
+    echo
+    printUsage "$0"
     exit 2
 elif [ "$render" = 'command' ]; then
     if [ -z "$EXTRACTMATCHES_COMMANDLINE" ]; then
-	echo >&2 'ERROR: Command reporting must define EXTRACTMATCHES_COMMANDLINE.'
+	echo 'ERROR: Command reporting must define EXTRACTMATCHES_COMMANDLINE.'
 	exit 2
     fi
     if [ "$EXTRACTMATCHES_PRE_COMMANDLINE" ]; then
@@ -448,7 +460,7 @@ elif [ "$render" = 'command' ]; then
 	EXEC=
 	trap "$EXTRACTMATCHES_POST_COMMANDLINE" EXIT
     fi
-fi
+fi >&2
 replacements+=(''); others+=(''); names+=('')	# Add one empty element so that split() will yield at least one in case of a single empty one.
 : ${EXTRACTMATCHES_COUNT_PREFIX="$(getCountPrefix)"}
 : ${EXTRACTMATCHES_COUNT_SUFFIX="$(getCountSuffix)"}
@@ -492,6 +504,7 @@ $EXEC awk \
     -v "overlayPrefix=${extractmatchesOverlayJump//\\/\\\\}${extractmatchesOverlayPrefix//\\/\\\\}" \
     -v "overlaySeparator=${extractmatchesOverlaySeparator//\\/\\\\}" \
     -v "overlaySuffix=${extractmatchesOverlaySuffix//\\/\\\\}${extractmatchesOverlayErase//\\/\\\\}${extractmatchesOverlayReturn//\\/\\\\}" \
+    -v "overlayClear=${isClear:+${extractmatchesOverlayClear//\\/\\\\}}" \
     -v "concatenatedUpdateDelay=${EXTRACTMATCHES_CONCATENATED_UPDATE_DELAY}" \
     -v "concatenatedPrefix=${EXTRACTMATCHES_CONCATENATED_PREFIX//\\/\\\\}" \
     -v "concatenatedSeparator=${EXTRACTMATCHES_CONCATENATED_SEPARATOR//\\/\\\\}" \
@@ -1149,9 +1162,14 @@ function process(type, start, len, pattern, replacement, other, name, priority, 
 }
 END {
     switch (render) {
-	case "overlay":
 	case "highlight":
 	case "flash":
+	    break
+	case "overlay":
+	    if (overlayClear != "") {
+		printf "%s", overlayClear > file
+		if (isBuffered) fflush(file)
+	    }
 	    break
 	case "concatenated":
 	    delayedConcatenatedRender()
