extractMatchesToPanel: Robustness: Minor: Add check for titleupdate

diff --git a/bin/extractMatchesToPanel b/bin/extractMatchesToPanel
--- a/bin/extractMatchesToPanel
+++ b/bin/extractMatchesToPanel
@@ -3,7 +3,7 @@
 printUsage()
 {
     extractMatches --help 2>&1 | sed \
-	-e '1s#^.*$#Locate passed PATTERNs in the input and duplicate the last of (or count occurrences of) them to the panel in the terminal'\''s window title, in order to emphasize and persist the information.#' \
+	-e '1s#^.*$#Locate passed PATTERNs in the input and duplicate the last of (or count occurrences of) them to the panel of the terminal'\''s window title, in order to emphasize and persist the information.#' \
 	-e '2b removeFirstParagraphLoop' \
 	-e '/^ *--to|-t/b removeOptionLoop' \
 	-e '/^\(Usage\|Example\):$/N' -e "/\(^\|\n\)\(Usage\|Example\): */{ s/\(^\|\n\)\(\(Usage\|Example\): *\)\?extractMatches /\1\2$(basename "$1") /; s/\[-t|--to [^]]\+\]// }" \
@@ -13,6 +13,11 @@ printUsage()
 case "$1" in
     --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 esac
+
+if ! type -t titleupdate >/dev/null; then
+    echo >&2 'ERROR: titleupdate is not available.'
+    exit 3
+fi
 
 EXTRACTMATCHES_COMMAND_UPDATE_DELAY=${EXTRACTMATCHES_PANEL_UPDATE_DELAY:-0} \
 EXTRACTMATCHES_POST_COMMANDLINE="titleupdate --id extractMatchesToPanel --clear 2>/dev/null" \
