no{out,err}: ENH: Consistency: Also support --exec
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/noout b/bin/noout
--- a/bin/noout
+++ b/bin/noout
@@ -1,13 +1,15 @@
 #!/bin/bash
 
 : ${NOOUT_COMMAND_JOINER=;}
+: ${NOOUT_EXEC_END=;}
 
 printUsage()
 {
     cat <<HELPTEXT
 Execute COMMAND while suppressing the stdout output.
 HELPTEXT
-printf 'Usage: %q %s\n' "$(basename "$1")" '-c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]'
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" "-c|--command \"COMMANDLINE\" [-c ...] | --exec SIMPLECOMMAND [...] ${NOOUT_EXEC_END} [--exec ...] | [--] SIMPLECOMMAND [...] [-?|-h|--help]"
 }
 
 commands=
@@ -16,6 +18,21 @@ do
     case "$1" in
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--command|-c)	shift; commands+="${commands:+ $NOOUT_COMMAND_JOINER }$1"; shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != "$NOOUT_EXEC_END" ]
+			do
+			    printf -v quotedArg %q "$1"
+			    cmd+="${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: --exec command must be concluded with '${NOOUT_EXEC_END}'"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+="${commands:+ $NOOUT_COMMAND_JOINER }${cmd}"
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
@@ -28,9 +45,8 @@ if [ $# -ne 0 ]; then
     commands+="${commands:+ $NOOUT_COMMAND_JOINER }${quotedSimpleCommand% }"
 fi
 if [ -z "$commands" ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo "ERROR: No COMMAND(s) specified; need to pass -c|--command \"COMMANDLINE\", or --exec SIMPLECOMMAND [...] $NOOUT_EXEC_END or SIMPLECOMMAND."
     exit 2
 fi
-
 
 eval "$commands" >/dev/null
