Optimization: Skip durationToSeconds invocation if [ADJUSTMENT-]TIMESPAN already is in [fractional] seconds
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/parseTimespanWithAdjustment b/bin/parseTimespanWithAdjustment
--- a/bin/parseTimespanWithAdjustment
+++ b/bin/parseTimespanWithAdjustment
@@ -71,20 +71,30 @@ if [ $# -ne 1 ]; then
 fi
 
 export DURATIONTOSECONDS_ACCEPT_FRACTIONAL="$PARSETIMESPANWITHADJUSTMENT_ACCEPT_FRACTIONAL"
+fractionPattern=''; [ "$DURATIONTOSECONDS_ACCEPT_FRACTIONAL" ] && fractionPattern='(\.[[:digit:]]+)?'
 
+timespan=
 adjustment=
 rawAdjustment=
 if [[ "$1" =~ ^(.*[^[:space:]])[[:space:]]*([+-])([[:space:]]*([0-9]+%)|[[:space:]]*([^[:space:]].*))$ ]]; then
     rawTimespan="${BASH_REMATCH[1]}"
     if [ -n "${BASH_REMATCH[4]}" ]; then
-	adjustment="${BASH_REMATCH[2]}${BASH_REMATCH[4]}"
+	adjustment="${BASH_REMATCH[2]}${BASH_REMATCH[4]}"   # percentage
     else
-	rawAdjustment="${BASH_REMATCH[2]}${BASH_REMATCH[5]}"
+	rawAdjustment="${BASH_REMATCH[2]}${BASH_REMATCH[5]}"	# timespan
+	if [[ "$rawAdjustment" =~ ^[[:digit:]]+${fractionPattern}$ ]]; then
+	    adjustment=$rawAdjustment
+	    rawAdjustment=''
+	fi
+    fi
+    if [[ "$rawTimespan" =~ ^[[:digit:]]+${fractionPattern}$ ]]; then
+	timespan=$rawTimespan
+	rawTimespan=''
     fi
 else
     rawTimespan="$1"
 fi
-timespan=$(durationToSeconds -- "${rawTimespan:?}") || { status=$?; printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$rawTimespan"; exit $status; }
+[ -z "$rawTimespan" ] || timespan=$(durationToSeconds -- "${rawTimespan:?}") || { status=$?; printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$rawTimespan"; exit $status; }
 [ -z "$rawAdjustment" ] || adjustment=$(DURATIONTOSECONDS_ACCEPT_SIGN=t durationToSeconds -- "$rawAdjustment") || { status=$?; printf >&2 'ERROR: Illegal ADJUSTMENT-TIMESPAN: %s\n' "$rawAdjustment"; exit $status; }
 
 [ -n "$adjustment" ] \
