prefix,suffix,surround: ENH: Allow wrapping output of passed COMMANDLINE or SIMPLECOMMAND
Sometimes it's helpful when a pipeline (CMD | prefix X) can be avoided via prefix --exec CMD \; X

diff --git a/bin/prefix b/bin/prefix
--- a/bin/prefix
+++ b/bin/prefix
@@ -6,8 +6,11 @@ printUsage()
 Prefix each individual line with PREFIX.
 HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-k|--keep-indent] [-s|--skip-empty] [--] PREFIX FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-k|--keep-indent] [-s|--skip-empty] -c|--command "COMMANDLINE" [...] | --exec SIMPLECOMMAND ... ; [...] [--] PREFIX'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-k|--keep-indent] [-s|--skip-empty] [--] PREFIX'
 }
+
+typeset -a commands=()
 isKeepIndent=
 additionalSedProcessing=()
 while [ $# -ne 0 ]
@@ -16,12 +19,28 @@ do
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--keep-indent|-k)	shift; isKeepIndent=t;;
 	--skip-empty|-s)	shift; additionalSedProcessing+=(-e '/^[[:space:]]*\r\?$/b');;
+	--command|-c)	shift; commands+=(${commands:+;} "$1"); shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != ';' ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: -exec command must be concluded with ;!"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
-if [ $# -eq 0 ]; then
+if [ $# -eq 0 ] || [ ${#commands[@]} -gt 0 -a $# -ne 1 ]; then
     printUsage "$0" >&2
     exit 2
 fi
@@ -30,4 +49,5 @@ prefix=$1; shift
 literalPrefix=$prefix
 literalPrefix=${literalPrefix//\\/\\\\}
 literalPrefix=${literalPrefix//&/\\&}
-exec sed "${additionalSedProcessing[@]}" -e "s#\\(^${isKeepIndent:+[[:space:]]*}\\)#\\1${literalPrefix//#/\\#}#" "$@"
+eval "${commands:+{ }" "${commands[@]:-exec}" "${commands:+" ; } |"}" \
+    'sed "${additionalSedProcessing[@]}" -e "s#\\(^${isKeepIndent:+[[:space:]]*}\\)#\\1${literalPrefix//#/\\#}#" "$@"'
diff --git a/bin/suffix b/bin/suffix
--- a/bin/suffix
+++ b/bin/suffix
@@ -6,8 +6,12 @@ printUsage()
 Append SUFFIX to each individual line.
 HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-k|--keep-whitespace] [-s|--skip-empty] [--] SUFFIX FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-k|--keep-whitespace] [-s|--skip-empty] -c|--command "COMMANDLINE" [...] | --exec SIMPLECOMMAND ... ; [...] [--] SUFFIX'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-k|--keep-whitespace] [-s|--skip-empty] [--] SUFFIX'
 }
+typeset -a commands=()
+
+typeset -a commands=()
 isKeepWhitespace=
 additionalSedProcessing=()
 while [ $# -ne 0 ]
@@ -16,12 +20,28 @@ do
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--keep-whitespace|-k)	shift; isKeepWhitespace=t;;
 	--skip-empty|-s)	shift; additionalSedProcessing+=(-e '/^[[:space:]]*\r\?$/b');;
+	--command|-c)	shift; commands+=(${commands:+;} "$1"); shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != ';' ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: -exec command must be concluded with ;!"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
-if [ $# -eq 0 ]; then
+if [ $# -eq 0 ] || [ ${#commands[@]} -gt 0 -a $# -ne 1 ]; then
     printUsage "$0" >&2
     exit 2
 fi
@@ -30,4 +50,5 @@ suffix=$1; shift
 literalSuffix=$suffix
 literalSuffix=${literalSuffix//\\/\\\\}
 literalSuffix=${literalSuffix//&/\\&}
-exec sed "${additionalSedProcessing[@]}" -e "s#\\(${isKeepWhitespace:+[[:space:]]*}\\r\\?\$\\)#${literalSuffix//#/\\#}\\1#" "$@"
+eval "${commands:+{ }" "${commands[@]:-exec}" "${commands:+" ; } |"}" \
+    'sed "${additionalSedProcessing[@]}" -e "s#\\(${isKeepWhitespace:+[[:space:]]*}\\r\\?\$\\)#${literalSuffix//#/\\#}\\1#" "$@"'
diff --git a/bin/surround b/bin/surround
--- a/bin/surround
+++ b/bin/surround
@@ -6,8 +6,10 @@ printUsage()
 Prepend PREFIX and append SUFFIX around each individual line.
 HELPTEXT
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-k|--keep-whitespace] [-s|--skip-empty] [--] PREFIX SUFFIX FILE [...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-k|--keep-whitespace] [-s|--skip-empty] -c|--command "COMMANDLINE" [...] | --exec SIMPLECOMMAND ... ; [...] [--] PREFIX SUFFIX '
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[-k|--keep-whitespace] [-s|--skip-empty] [--] PREFIX SUFFIX'
 }
+typeset -a commands=()
 isKeepWhitespace=
 additionalSedProcessing=()
 while [ $# -ne 0 ]
@@ -16,12 +18,28 @@ do
 	--help|-h|-\?)	shift; printUsage "$0"; exit 0;;
 	--keep-whitespace|-k)	shift; isKeepWhitespace=t;;
 	--skip-empty|-s)	shift; additionalSedProcessing+=(-e '/^[[:space:]]*\r\?$/b');;
+	--command|-c)	shift; commands+=(${commands:+;} "$1"); shift;;
+	--exec)		shift
+			cmd=
+			while [ $# -gt 0 -a "$1" != ';' ]
+			do
+			    printf -v quotedArg '%q' "$1"
+			    cmd="${cmd}${cmd:+ }${quotedArg}"
+			    shift
+			done
+			if [ $# -eq 0 ]; then
+			    echo "ERROR: -exec command must be concluded with ;!"; echo; printUsage "$0"
+			    exit 2
+			fi >&2
+			shift
+			commands+=(${commands:+;} "$cmd")
+			;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
     esac
 done
-if [ $# -le 1 ]; then
+if [ $# -le 1 ] || [ ${#commands[@]} -gt 0 -a $# -ne 2 ]; then
     printUsage "$0" >&2
     exit 2
 fi
@@ -36,4 +54,5 @@ literalSuffix=$suffix
 literalSuffix=${literalSuffix//\\/\\\\}
 literalSuffix=${literalSuffix//&/\\&}
 
-exec sed "${additionalSedProcessing[@]}" -e "s#\\(^${isKeepWhitespace:+[[:space:]]*}\\)\\(.*[^${isKeepWhitespace:+^[:space:]}\\r]\\|\\)\\(${isKeepWhitespace:+[[:space:]]*}\\r\\?\$\\)#\\1${literalPrefix//#/\\#}\\2${literalSuffix//#/\\#}\\3#" "$@"
+eval "${commands:+{ }" "${commands[@]:-exec}" "${commands:+" ; } |"}" \
+    'sed "${additionalSedProcessing[@]}" -e "s#\\(^${isKeepWhitespace:+[[:space:]]*}\\)\\(.*[^${isKeepWhitespace:+^[:space:]}\\r]\\|\\)\\(${isKeepWhitespace:+[[:space:]]*}\\r\\?\$\\)#\\1${literalPrefix//#/\\#}\\2${literalSuffix//#/\\#}\\3#" "$@"'
