sampleLines: Reimplementation: Reuse durationToSeconds / parseTimespanWithAdjustment for timespan / initial delay
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/sampleLines b/bin/sampleLines
--- a/bin/sampleLines
+++ b/bin/sampleLines
@@ -29,7 +29,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" "[-r|--reset-on PATTERN [-r ...]] [-i|--inline-or-none|--inline-or-passthrough|-I|--inline-always [--inline-prefix IP] [-c|--clear] [-a|--append-reset|-k|--keep-reset]] [--transform-command TRANSFORM-COMMAND [--transform-command ...] | --transform-exec SIMPLECOMMAND [...] ${SAMPLELINES_EXEC_END} [--transform-exec ...]] [-S|--summarize WHAT[,PLURAL-WHAT] --summary-only] [-n|--count WHAT] [-s|--skip PATTERN [-s ...]] [-m|--match PATTERN [-m ...]] [-t|--timespan TIMESPAN[SUFFIX][ADJUSTMENT]] [-T|--initial-delay TIMESPAN[SUFFIX]] [-?|-h|--help]"
+    printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" "[-r|--reset-on PATTERN [-r ...]] [-i|--inline-or-none|--inline-or-passthrough|-I|--inline-always [--inline-prefix IP] [-c|--clear] [-a|--append-reset|-k|--keep-reset]] [--transform-command TRANSFORM-COMMAND [--transform-command ...] | --transform-exec SIMPLECOMMAND [...] ${SAMPLELINES_EXEC_END} [--transform-exec ...]] [-S|--summarize WHAT[,PLURAL-WHAT] --summary-only] [-n|--count WHAT] [-s|--skip PATTERN [-s ...]] [-m|--match PATTERN [-m ...]] [-t|--timespan $(parseTimespanWithAdjustment --get-short-usage format)] [-T|--initial-delay TIMESPAN] [-?|-h|--help]"
 }
 printUsage()
 {
@@ -48,6 +48,8 @@ discard additional lines.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
+    echo
+    local timespanFormat="$(durationToSeconds --get-short-usage format 2>/dev/null)"
     cat <<HELPTEXT
     --reset-on|-r PATTERN
 			Reset the sampling interval on lines matching PATTERN,
@@ -95,19 +97,11 @@ HELPDESCRIPTION
     --match|-m PATTERN	Only consider lines that match PATTERN when counting
 			(both for summary and total counts); other lines (and
 			those that also match --skip PATTERN) are ignored.
-    --timespan|-t TIMESPAN[SUFFIX][ADJUSTMENT]
-			Print a line every TIMESPAN instead of every second.
-			SUFFIX may be 'ms' for milliseconds, 's' for seconds
-			(the default), 'm' for minutes, 'h' for hours or 'd' for
-			days. ADJUSTMENT can change the original value after
-			every iteration. It starts with either + or -, followed
-			by another TIMESPAN, optionally followed by either
-			SUFFIX or %.
-			For example, 10m+30s starts with 10 minutes and then
-			increases that by 30 seconds on every iteration. 10-5%
-			starts with 10 seconds and then continually decreases
-			that by 5 percent.
-    --initial-delay|-T TIMESPAN[SUFFIX]
+HELPTEXT
+    parseTimespanWithAdjustment --get-long-usage '--timespan|-t' 'Print a line every [adjusted] TIMESPAN instead of every
+			second.'
+    cat <<HELPTEXT
+    --initial-delay|-T $timespanFormat
 			Wait for TIMESPAN before printing anything. By default,
 			the first line is printed immediately.
 All PATTERNs are POSIX-style unanchored extended regular expressions.
@@ -120,40 +114,6 @@ HELPTEXT
 
     printf 'ping localhost | %q %s\n' "$(basename "$1")" '--inline-or-none --clear -t 3'
     printf 'ping -c 10 localhost | tee >(%q %s >/dev/tty) | tail -n 1 | delay 1s\n' "$(basename "$1")" '--inline-or-none --clear -t 3'
-}
-timeToSeconds()
-{
-    case "$1" in
-	+([0-9])ms)	if [ -n "$adjustment" ]; then
-			    echo >&2 'ERROR: Cannot combine millisecond interval with adjustment.'
-			    exit 2
-			fi
-			time="00${1%ms}"; time="0${time%???}.${time:$((${#time}-3))}"; time="${time/#+(0)/0}"
-			;;
-	+([0-9])?(s))   time="${1%s}";;
-	+([0-9])m)	time=$((${1%m} * 60));;
-	+([0-9])h)	time=$((${1%h} * 3600));;
-	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 "ERROR: Illegal ${2:-timespan}: %s\\n" "$1"; exit 2;;
-    esac
-    printf %s "$time"
-}
-timeWithAdjustmentToSeconds()
-{
-    local adjustment="${1##+([0-9])?([smhd]|ms)}"
-    local time="${1:0:$((${#1} - ${#adjustment}))}"
-    if [ -z "$time" ]; then
-	printf >&2 'ERROR: Empty timespan: %s\n' "$time"; exit 2;
-    fi
-    case "$adjustment" in
-	'')		    ;;
-	[+-]+([0-9])?(%))   ;;
-	++([0-9])[smhd])    adjustment="+$(timeToSeconds "${adjustment#+}" adjustment)" || return $?;;
-	-+([0-9])[smhd])    adjustment="-$(timeToSeconds "${adjustment#-}" adjustment)" || return $?;;
-	*)		    printf >&2 'ERROR: Illegal adjustment: %s\n' "$adjustment"; exit 2;;
-    esac
-    time="$(timeToSeconds "$time" "$2")" || exit $?
-    printf '%s\t%s\n' "$time" "$adjustment"
 }
 adjust()
 {
@@ -265,9 +225,9 @@ do
 	--count|-n)	shift; totalCountWhat="$1"; shift;;
 	--skip|-s)	shift; skipPattern+="${skipPattern:+|}${1:?}"; shift;;
 	--match|-m)	shift; matchPattern+="${matchPattern:+|}${1:?}"; shift;;
-	--timespan|-t)	shift; < <(timeWithAdjustmentToSeconds "$1") IFS=$'\t' read -r timespan timespanAdjustment || exit 2; shift;;
+	--timespan|-t)	shift; < <(parseTimespanWithAdjustment -- "${1:?}") IFS=$'\t' read -r timespan timespanAdjustment || exit 2; shift;;
 	--initial-delay|-T)
-			shift; initialDelay="$(timeToSeconds "$1")" || exit $?; shift;;
+			shift; initialDelay=$(durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		break;;
