FIX: adjustment with SUFFIX needs to be converted into +SECONDS / -SECONDS
As adjust() only deals with percentages or seconds. Need to invoke timeToSeconds() while maintaining the sigil outside.

diff --git a/bin/sampleLines b/bin/sampleLines
--- a/bin/sampleLines
+++ b/bin/sampleLines
@@ -112,7 +112,7 @@ timeToSeconds()
 	+([0-9])m)	time=$((${1%m} * 60));;
 	+([0-9])h)	time=$((${1%h} * 3600));;
 	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 'ERROR: Illegal timespan: %s\n' "$1"; exit 2;;
+	*)		printf >&2 "ERROR: Illegal ${2:-timespan}: %s\\n" "$1"; exit 2;;
     esac
     printf %s "$time"
 }
@@ -124,9 +124,11 @@ timeWithAdjustmentToSeconds()
 	printf >&2 'ERROR: Empty timespan: %s\n' "$time"; exit 2;
     fi
     case "$adjustment" in
-	'')			;;
-	[+-]+([0-9])?([smhd%]))	;;
-	*)  printf >&2 'ERROR: Illegal adjustment: %s\n' "$adjustment"; exit 2;;
+	'')		    ;;
+	[+-]+([0-9])?(%))   ;;
+	++([0-9])[smhd])    adjustment="+$(timeToSeconds "${adjustment#+}" adjustment)" || return $?;;
+	-+([0-9])[smhd])    adjustment="-$(timeToSeconds "${adjustment#-}" adjustment)" || return $?;;
+	*)		    printf >&2 'ERROR: Illegal adjustment: %s\n' "$adjustment"; exit 2;;
     esac
     time="$(timeToSeconds "$time" "$2")" || exit $?
     printf '%s\t%s\n' "$time" "$adjustment"
