Documentation: Tweak --summarize functionality
Combining --tally and --summarize would be difficult to implement, as both would need the record continuation algorithm - with different filtering (and one printing records, and the latter storing for a final summary). Also, the separation of both outputs is awkward to handle, and would make parsing of that output cumbersome.
I think it's better to limit the application's ability to one task; if both are needed, it would have to be invoked multiple times on the same source files (or using tee). That would have been necessary for multiple summaries or tallies, anyway.

diff --git a/bin/timestampTally b/bin/timestampTally
--- a/bin/timestampTally
+++ b/bin/timestampTally
@@ -1,13 +1,11 @@
 #!/bin/bash
 shopt -qs extglob
 
-: ${TIMESTAMPTALLY_SUMMARY_SEPARATOR=$'\nSummary:\n'}
-
 printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--unbuffered] [-F|--field-separator FS] [--timestamp-field N[-M] [--max-difference DURATION[SUFFIX] [--max-record-duration DURATION[SUFFIX]] [--max-record-length N]] [--entry-duration DURATION[SUFFIX]] [--single-entry-duration DURATION[SUFFIX]] [--tally LIST|PATTERN] [--summarize LIST|PATTERN] [--keep-timestamp start|end|both-concatenated|both-separate] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--unbuffered] [-F|--field-separator FS] [--timestamp-field N[-M] [--max-difference DURATION[SUFFIX] [--max-record-duration DURATION[SUFFIX]] [--max-record-length N]] [--entry-duration DURATION[SUFFIX]] [--single-entry-duration DURATION[SUFFIX]] [--tally LIST|PATTERN|--summarize LIST|PATTERN] [--keep-timestamp start|end|both-concatenated|both-separate] [FILE ...] [-?|-h|--help]'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[...]'
 }
 printUsage()
@@ -78,12 +76,10 @@ HELPDESCRIPTION
     --summarize LIST|PATTERN
 			    All subsequent lines where the fields in LIST / the
 			    first match of PATTERN are identical contribute to
-			    the record duration, which are summed up and
-			    reported at the end for each unique field value /
-			    pattern match.
-			    If both --tally and --summarize are given, the
-			    respective outputs are separated by
-			    TIMESTAMPTALLY_SUMMARY_SEPARATOR.
+			    the record duration, which is summed up and reported
+			    (in the form "duration OFS fields / match") at the
+			    end for each unique field value / pattern match,
+			    sorted by first occurrence.
     --keep-timestamp start  Instead of replacing the timestamp, put the duration
 			    after it (separated by OFS).
     --keep-timestamp end    Instead of replacing the timestamp of the line that
@@ -101,6 +97,7 @@ HELPDESCRIPTION
 			    line that concludes the record, so each tally will
 			    consist of two lines instead of one (except those
 			    from a single discontinuous line).
+			    (Does not work for --summarize.)
 
 EXIT STATUS:
     0	Complete success.
@@ -135,7 +132,7 @@ maxRecordLength=
 entryDuration=0
 singleEntryDuration=
 tally=
-summarize=
+isSummarize=
 keepTimestamp=
 while [ $# -ne 0 ]
 do
@@ -153,13 +150,28 @@ do
 	--entry-duration)   shift; entryDuration="$(timeToSeconds "$1")" || exit $?; shift;;
 	--single-entry-duration)
 			    shift; singleEntryDuration="$(timeToSeconds "$1")" || exit $?; shift;;
-	--tally)	    shift; tally="$1"; shift;;
-	--summarize)	    shift; summarize="$1"; shift;;
+	--tally)	    shift
+			    if [ "$isSummarize" ]; then
+				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printShortUsage "$0"; } >&2
+				exit 2
+			    fi
+			    tally="$1"
+			    shift
+			    ;;
+	--summarize)	    shift
+			    if [ ! "$isSummarize" ] && [ -n "$tally" ]; then
+				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printShortUsage "$0"; } >&2
+				exit 2
+			    fi
+			    tally="$1"
+			    isSummarize=t
+			    shift
+			    ;;
 	--keep-timestamp)   shift
 			    keepTimestamp="$1"
 			    case "$keepTimestamp" in
 				start|end|both-concatenated|both-separate)  ;;
-				*)  printf >&2 'ERROR: Invalid value for --keep-timestamp: %s\n' "$keepTimestamp"; printShortUsage >&2 "$0"; exit 2;;
+				*)  { printf 'ERROR: Invalid value for --keep-timestamp: %s\n' "$keepTimestamp"; echo; printShortUsage "$0"; } >&2; exit 2;;
 			    esac
 			    shift
 			    ;;
@@ -182,7 +194,6 @@ fi
 [ -z "$singleEntryDuration" ] && singleEntryDuration=$entryDuration
 
 awk \
-    -v "summarySeparator=${TIMESTAMPTALLY_SUMMARY_SEPARATOR//\\/\\\\}" \
     -v "isBuffered=$isBuffered" \
     -v "timestampField=${timestampField//\\/\\\\}" \
     -v "maxDifference=$maxDifference" \
@@ -191,7 +202,7 @@ awk \
     -v "entryDuration=$entryDuration" \
     -v "singleEntryDuration=$singleEntryDuration" \
     -v "tally=${tally//\\/\\\\}" \
-    -v "summarize=${summarize//\\/\\\\}" \
+    -v "isSummarize=$isSummarize" \
     -v "keepTimestamp=$keepTimestamp" \
     "${awkArgs[@]}" \
 '
