Usability: Ensure that --max-record-duration is used together with --max-difference

diff --git a/bin/timestampTally b/bin/timestampTally
--- a/bin/timestampTally
+++ b/bin/timestampTally
@@ -7,7 +7,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--unbuffered] [-F|--field-separator FS] [--timestamp-field N[-M] [--max-difference DURATION[SUFFIX]] [--max-record-duration DURATION[SUFFIX]] [--single-entry-duration DURATION[SUFFIX]] [--tally LIST|PATTERN] [--summarize LIST|PATTERN] [--keep-timestamp start|end|both-concatenated|both-separate] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--unbuffered] [-F|--field-separator FS] [--timestamp-field N[-M] [--max-difference DURATION[SUFFIX] [--max-record-duration DURATION[SUFFIX]]] [--single-entry-duration DURATION[SUFFIX]] [--tally LIST|PATTERN] [--summarize LIST|PATTERN] [--keep-timestamp start|end|both-concatenated|both-separate] [FILE ...] [-?|-h|--help]'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[...]'
 }
 printUsage()
@@ -50,9 +50,11 @@ HELPDESCRIPTION
 			    (the default), 'm' for minutes, 'h' for hours or
 			    'd' for days.
     --max-record-duration DURATION[SUFFIX]
-			    If the temporal difference between the a record's
+			    If the temporal difference between the record's
 			    first line and the current line is larger than
-			    DURATION, a new record is started.
+			    DURATION, a new record is started. This can be used
+			    to cut off regular updates that all all within
+			    --max-difference after a while.
     --single-entry-duration DURATION[SUFFIX]
 			    A single discontinuous record is counted as being
 			    DURATION long.
@@ -151,6 +153,12 @@ do
 	*)		    break;;
     esac
 done
+if [ -n "$maxRecordDuration" -a "$maxDifference" = 0 ]; then
+    echo >&2 'ERROR: --max-record-duration can only be used together with --max-difference.'
+    echo >&2
+    printShortUsage "$0" >&2
+    exit 2
+fi
 
 awk \
     -v "summarySeparator=${TIMESTAMPTALLY_SUMMARY_SEPARATOR//\\/\\\\}" \
