timestampTally: Reimplementation: Minor: Replace timeToSeconds() with delegation to durationToSeconds
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/timestampTally b/bin/timestampTally
--- a/bin/timestampTally
+++ b/bin/timestampTally
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-u|--unbuffered] [-F|--field-separator FS] [--timestamp-field N[-M] [--max-difference DURATION[SUFFIX] [--max-record-duration DURATION[SUFFIX]] [--max-record-length N]] [--entry-duration DURATION[SUFFIX]] [--single-entry-duration DURATION[SUFFIX]] [--tally LIST|PATTERN|--summarize LIST|PATTERN] [--keep-timestamp start|end|both-concatenated|both-separate|--keep-epoch start|end|both-concatenated|both-separate] [FILE ...] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-u|--unbuffered] [-F|--field-separator FS] [--timestamp-field N[-M] [--max-difference TIMESPAN [--max-record-duration TIMESPAN] [--max-record-length N]] [--entry-duration TIMESPAN] [--single-entry-duration TIMESPAN] [--tally LIST|PATTERN|--summarize LIST|PATTERN] [--keep-timestamp start|end|both-concatenated|both-separate|--keep-epoch start|end|both-concatenated|both-separate] [FILE ...] [-?|-h|--help]'
     printf 'Usage: cat FILE [...] | %q %s\n' "$(basename "$1")" '[...]'
 }
 printUsage()
@@ -26,6 +26,8 @@ single tally line and/or any lines into a final summary.
 HELPDESCRIPTION
     echo
     printShortUsage "$1"
+    echo
+    local timespanFormat="$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds --get-short-usage format 2>/dev/null)"
     cat <<HELPTEXT
     --unbuffered|-u	    Immediately output each record.
     --field-separator|-F FS Use FS as the input field separator (as with AWK).
@@ -38,19 +40,16 @@ HELPDESCRIPTION
 			    fields with the default field separator here)
 			    Lines that do not contain a valid timestamp are
 			    redirected to standard error.
-    --max-difference DURATION[SUFFIX]
+    --max-difference ${timespanFormat:-TIMESPAN}
 			    If the temporal difference between two subsequent
-			    lines is larger than DURATION, the records are
+			    lines is larger than TIMESPAN, the records are
 			    treated as discontinuous and a separate tally is
 			    started. Without this, any temporal difference
 			    separates records.
-			    SUFFIX may be 'ms' for milliseconds, 's' for seconds
-			    (the default), 'm' for minutes, 'h' for hours or
-			    'd' for days.
-    --max-record-duration DURATION[SUFFIX]
+    --max-record-duration ${timespanFormat:-TIMESPAN}
 			    If the temporal difference between the record's
 			    first line and the current line is larger than
-			    DURATION, a new record is started. This can be used
+			    TIMESPAN, a new record is started. This can be used
 			    to separate regularly appearing updates (that all
 			    fall within --max-difference) after a while.
     --max-record-length N   If a record would span more than N lines, a new
@@ -58,13 +57,13 @@ HELPDESCRIPTION
 			    separate regularly appearing updates (that all fall
 			    within --max-difference) after a certain amount of
 			    data.
-    --entry-duration DURATION[SUFFIX]
-			    Each record is counted as being DURATION long,
+    --entry-duration ${timespanFormat:-TIMESPAN}
+			    Each record is counted as being TIMESPAN long,
 			    instead of being just an infinitesimal short point
 			    in time.
-    --single-entry-duration DURATION[SUFFIX]
+    --single-entry-duration ${timespanFormat:-TIMESPAN}
 			    A single discontinuous record is counted as being
-			    DURATION long. With this, you can make single
+			    TIMESPAN long. With this, you can make single
 			    entries count differently than continuous lines.
     --tally LIST|PATTERN    All subsequent lines where the fields in LIST / the
 			    first match of PATTERN are identical are condensed
@@ -114,18 +113,6 @@ HELPTEXT
     printf '%q %s\n' "$(basename "$1")" '--max-difference 3 --entry-duration 1 --summarize 3 /var/log/dpkg.log'
 }
 
-timeToSeconds()
-{
-    case "$1" in
-	+([0-9])ms)	time="00${1%ms}"; time="0${time%???}.${time:$((${#time}-3))}"; time="${time/#+(0)/0}";;
-	+([0-9])?(s))   time="${1%s}";;
-	+([0-9])m)	time=$((${1%m} * 60));;
-	+([0-9])h)	time=$((${1%h} * 3600));;
-	+([0-9])d)	time=$((${1%d} * 86400));;
-	*)		printf >&2 "ERROR: Illegal ${2:-duration}: %s\\n" "$1"; exit 2;;
-    esac
-    printf %s "$time"
-}
 typeset -a awkArgs=()
 isBuffered=t
 timestampField=
@@ -146,14 +133,14 @@ do
 	--field-separator|-F)
 			    awkArgs+=("$1" "$2"); shift; shift;;
 	--timestamp-field)  shift; timestampField="$1"; shift;;
-	--max-difference)   shift; maxDifference="$(timeToSeconds "$1")" || exit $?; shift;;
+	--max-difference)   shift; maxDifference=$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--max-record-duration)
-			    shift; maxRecordDuration="$(timeToSeconds "$1")" || exit $?; shift;;
+			    shift; maxRecordDuration=$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--max-record-length)
 			    shift; maxRecordLength="$1"; shift;;
-	--entry-duration)   shift; entryDuration="$(timeToSeconds "$1")" || exit $?; shift;;
+	--entry-duration)   shift; entryDuration=$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--single-entry-duration)
-			    shift; singleEntryDuration="$(timeToSeconds "$1")" || exit $?; shift;;
+			    shift; singleEntryDuration=$(DURATIONTOSECONDS_ACCEPT_FRACTIONAL=t durationToSeconds -- "${1:?}") || { printf >&2 'ERROR: Illegal TIMESPAN: %s\n' "$1"; exit 2; }; shift;;
 	--tally)	    shift
 			    if [ "$isSummarize" ]; then
 				{ echo "ERROR: Cannot combine --tally with --summarize."; echo; printUsage "$0"; } >&2
