uncolor: Robustness: Do not accept unknown -* options

diff --git a/bin/uncolor b/bin/uncolor
--- a/bin/uncolor
+++ b/bin/uncolor
@@ -105,6 +105,7 @@ do
 			fi
 			shift; shift
 			;;
+	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		if ! sequence="$(getSequence "$1")"; then
 			    printUsage "$0" >&2
 			    exit 2
